### PR TITLE
Darwin Core mapping

### PR DESCRIPTION
**Pull request by LienReyserhove**
This pull request contains the mapping of the terrestrial mollusc data to Darwin Core. 
Below a summary of all terms (for description extension: all descriptors).
Please tick off the boxes when the mapping of the term/descriptor is ok.

TAXON CORE
- [x] language
- [x] license 
- [x] rightsHolder
- [x] datasetID
- [x] institutionCode
- [x] datasetName
- [x] taxonID
- [x] acceptedNameUsageID
- [x] originalNameUsageID
- [x] scientificName
- [x] acceptedNameUsage
- [x] originalNameUsage
- [x] kingdom
- [x] phylum
- [x] class
- [x] order
- [x] family
- [x] genus
- [x] taxonRank
- [x] nomenclaturalCode
- [x] taxonomicStatus
- [x] taxonRemarks

VERNACULAR NAMES
- [x] taxonID
- [x] vernacularName
- [x] language

DISTRIBUTION EXTENSION
- [x] taxonID
- [x] locationID
- [x] locality
- [x] countryCode
- [x] occurrenceStatus
- [x] establishmentMeans
- [x] eventDate
- [x] source

LITERATURE REFERENCES
- [x] taxonID
- [x] identifier
- [x] bibliographicCitation

DESCRIPTION EXTENSION
- [x] native range
- [x] introduction pathway
- [x] degree of establishment

### CODE REVIEW

**Comment by peterdesmet** [comment]
## taxa

- [x] `rightsHolder` would opt for `RBINS` rather than full name. That would make it the same as `institutionCode`
- [x] `originalNameUsageID` and `originalNameUsage`: would remove (is also empty for some), see #12.
- [x] `scientificName`:  is empty for `alien-mollusca-checklist:taxon:55611e71b358a30158c61810ad802435`, due to empty value in synonym list **corrected**
- [x] `taxonRank`: missing from dataset - **was included in mapping but without `dwc_` prefix, hence removed afterwards. ok now**
- [x] `taxonomicStatus`: see #12
- [x] `taxonRemarks`: missing from dataset

## vernacularNames

- [x] No vernacular name for `Striosubulina striatella (Rang, 1831)`? **no, is correct**
- [x] `language`: use iso codes `en`, `fr`, `de`, `nl` - **corrected, error in R code**

## Distribution

- [x] No source for `alien-mollusca-checklist:taxon:81d4efabef9ab3e384dfe016ee69d01f` (`Allopeas clavulinum (Potiez & Michaud, 1835)`)? **Forgotten by Thierry, I added one**
- [x] `eventDate`:  `after 1944 ?` Would use `1944`
- [x] `eventDate`: why not date ranges (until 2019) for all? **No, Thierry does not agree**

## Description

- [x] Is `blackburn_et_al_2011` the best prefix for `degree of establishment` values @qgroom? 
- [x] Do we keep `unclear` as a native range? **For Thierry to decide, I would keep it**

## References

- [x] No ref for `Striosubulina striatella (Rang, 1831)`? **corrected**
- [x] Some identifiers are double: #13

**Review by peterdesmet — CHANGES_REQUESTED** [review]
See https://github.com/trias-project/alien-mollusca-checklist/pull/11#issuecomment-488667980

**Comment by LienReyserhove** [comment]
Thanks for the review! My comments are integrated in bold in the previous text. Some terms requested more information, see below:

> (rightsHolder) would opt for RBINS rather than full name. That would make it the same as institutionCode

I wouldn't. We use full names for e.g. manual of alien plants, alien macroinvertebrates or RINSE (but not for alien fishes...). I would strive to always use the full name (see also the example in the [quick reference guide](http://rs.tdwg.org/dwc/terms/#dcterms:rightsHolder)).

>  (description) Is `blackburn_et_al_2011` the best prefix for `degree of establishment` values @qgroom? 

This is the source of the vocabulary, so why not refer to it?

**Comment by peterdesmet** [comment]
Regarding rightsholder: ok to use full name, but would keep using `INBO` for INBO datasets.

`blackburn_et_al_2011`: ok

I noticed some errors in taxonRank: will create separate issue.

**Review by peterdesmet — CHANGES_REQUESTED** [review]
Minor changes:

- pull in data again to fix some typos in sources
- use `:1` in `taxonID` for `Helix balteata Pollonera, 1892`
- use `proParteSynonym` in `taxonomicStatus` for `Helix balteata Pollonera, 1892`

Almost there 💨

**Comment by LienReyserhove** [comment]
Integrated!

**Review by peterdesmet — APPROVED** [review]

**Pull request merged**
